let arrlang = {
    'en': {
        'betaTesterBtn': 'Become a beta tester',
        'title': 'This is Mountiary',
        'bannerText': `He's here to help bring ideas to life.`,
        'prefsTitle': 'Why is it necessary to write down your thoughts?',
        'prefCellTitle1': 'It is easier to focus on the topic of reasoning',        
        'prefCellTitle2': 'You can write whatever you want and however you want',        
        'prefCellTitle3': 'Better experienced emotions are expressed and realized in writing',        
        'prefCellTitle4': 'In written discussions, insights about your life often arise',        
        'prefCellTitle5': 'You learn to listen to yourself,',        
        'prefCellTitle6': 'Imaginative thinking develops, which captures the whole picture of what is happeningIt is easier to focus on the topic of reasoning',        
        'prefCellText1': 'We are less distracted, and if we are distracted, we can easily review the recordings and return to our reasoning',        
        'prefCellText2': 'This is not an essay, but a stream of thoughts, experiences and ideas. These may be events that excite you, worries about something, thinking about something',        
        'prefCellText3': 'It is safe to express your negative emotions if it is not possible to express them directly. After all, negative emotions that have not found a way out get stuck in the body, creating blocks, as a result, the body fails',        
        'prefCellText4': `It's like finding a splinter that you can't see. Also in written arguments. You first write about what is painful, and then you have an epiphany: "So that's what's the matter!" or "So you can try to do this, and suddenly it turns out!"`,        
        'prefCellText5': 'to your thoughts, to your painful topics, learn to express and understand your emotions about various situations, learn to be aware of your satisfied needs and unsatisfied ones',        
        'prefCellText6': 'Logical thinking is more conservative, stable, and responsible for survival. Therefore, everything unknown to him falls into the category of incorrect and frightening',        
        'prefsTitle2': `That's why we came up with a completely new space inspired by the mountains`,
        'galleryTitle': 'Working on Mountiary',
        'galleryDesc': 'Our Teamname team has been fulfilling a common dream for more than two years now',
        'articlesTitle': 'Project news',
        'article1Title': '>Letter from the CEO',
        'article2Title': '>New in Mountiary!',
        'article3Title': '>Feedback from the most important member of our team',
        'article1Desc': 'Ivan Ivanov shared his thoughts and hopes about Mountiary.',
        'article2Desc': 'An article about the new features of the space, as well as fixed bugs found by our beta testers.',
        'article3Desc': 'The most important news of the last week. Read to everyone!',
        'article1Content': '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae tenetur nisi quasi quis velit quidem quos facilis tempora. Ut officia reiciendis sequi dignissimos! Reiciendis eius cupiditate accusamus, ipsam quae quam inventore maxime unde adipisci! Eum repellendus enim rem, numquam nam eligendi esse! Fuga omnis, quibusdam unde cumque impedit dolor soluta.',
        'article2Content': '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae tenetur nisi quasi quis velit quidem quos facilis tempora. Ut officia reiciendis sequi dignissimos! Reiciendis eius cupiditate accusamus, ipsam quae quam inventore maxime unde adipisci! Eum repellendus enim rem, numquam nam eligendi esse! Fuga omnis, quibusdam unde cumque impedit dolor soluta.',
        'article3Content': '>Woof woof woof, woof woof. Woof, woof woof woof-woof. Woof!',
        'articleBtn': 'More',
        'articleDate1': '25 jun 2023',
        'articleDate2': '23 jun 2023',
        'articleDate3': '19 jun 2023',
        'formTitle': 'Submit a request for beta testing',
        'formBtn': 'Join us!',
        'link1': 'We on VK',
        'link2': 'We on YouTube',
        'link3': 'We on Behance'
    },
    'ru': {
        'betaTesterBtn': 'Стать бета-тестером',
        'title': 'Это Mountiary',
        'bannerText': `Он здесь, чтобы помочь воплотить идеи в жизнь`,
        'prefsTitle': 'Почему необходимо записывать свои мысли?',
        'prefCellTitle1': 'Легче сосредоточиться на теме рассуждения',        
        'prefCellTitle2': 'Можно писать что вздумается и как захочется',        
        'prefCellTitle3': 'В письменной форме выражаются и осознаются лучше переживаемые эмоции',        
        'prefCellTitle4': 'В письменных рассуждениях часто возникают инсайты, касаемые вашей жизни',        
        'prefCellTitle5': 'Вы учитесь прислушиваться к себе,',        
        'prefCellTitle6': 'Развивается образное мышление, которое схватывает картинку происходящего целиком',        
        'prefCellText1': 'Мы меньше отвлекаемся, а если и отвлечемся, то с легкостью можем просмотреть записи и вернуться к своим рассуждениям',        
        'prefCellText2': 'Это не сочинение, а поток мыслей, переживаний и идей. Это могут быть события, которые вас волнуют, переживания по поводу чего-то, размышление о чем-то',        
        'prefCellText3': 'Можно безопасно выражать свои негативные эмоции, если нет возможности выразить их напрямую. Ведь негативные эмоции не нашедшие выхода, застревают в теле, создавая блоки, в результате организм дает сбой',        
        'prefCellText4': `Это словно найти занозу, которую не видно. Также и в письменных рассуждениях. Вы сначала пишите о наболевшем, а потом возникает озарение: " Так вот в чем дело!" или же " Так можно попробовать сделать так-то, а вдруг получится!"`,        
        'prefCellText5': 'к своим мыслям, к своим наболевшим темам, учитесь выражать и понимать свои эмоции по поводу различных ситуаций, учитесь осознавать свои удовлетворенные потребности и неудовлетворенные',        
        'prefCellText6': 'Логическое мышление более консервативно, стабильно, ответственно за выживание. Поэтому все неизвестное для него, попадает в категорию неверного и пугающего',        
        'prefsTitle2': `Поэтому мы и придумали совершенно новое пространство, вдохновленное горами`,
        'galleryTitle': 'Работа над Mountiary',
        'galleryDesc': 'Наша команда Teamname исполняет общую мечту уже больше двух лет',
        'articlesTitle': 'Новости проекта',
        'article1Title': '>Письмо от генерального директора',
        'article2Title': '>Новинки в Mountiary!',
        'article3Title': '>Отзыв самого главного члена нашей команды',
        'article1Desc': 'Иван Иванов поделился своими мыслями и надеждами о Mountiary.',
        'article2Desc': 'Статья о новых функциях пространства, а также исправленных багах, найденных нашими бета-тестерами.',
        'article3Desc': 'Самая главная новость последней недели. Читать всем!',
        'article1Content': '>Есть над чем задуматься: интерактивные прототипы представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Лишь базовые сценарии поведения пользователей призывают нас к новым свершениям, которые, в свою очередь, должны быть своевременно верифицированы. Вот вам яркий пример современных тенденций — сплочённость команды профессионалов предоставляет широкие возможности для инновационных методов управления процессами.',
        'article2Content': '>Есть над чем задуматься: интерактивные прототипы представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Лишь базовые сценарии поведения пользователей призывают нас к новым свершениям, которые, в свою очередь, должны быть своевременно верифицированы. Вот вам яркий пример современных тенденций — сплочённость команды профессионалов предоставляет широкие возможности для инновационных методов управления процессами.',
        'article3Content': '>Гав гав гав, гав гав. Гав, гав гав гав-гав. Гав!',
        'articleBtn': 'Читать полностью',
        'articleDate1': '25 июн 2023',
        'articleDate2': '23 июн 2023',
        'articleDate3': '19 июн 2023',
        'formTitle': 'Оставить заявку на бета-тестирование',
        'formBtn': 'Присоединиться к команде!',
        'link1': 'Мы во Вконтакте',
        'link2': 'Мы на YouTube',
        'link3': 'Мы на Behance'
    }
}

$(function () {
    $('.translate').click(function () {
        let lang = $(this).attr('id');
        $('.lang').each(function () {
            $(this).text(arrlang[lang][$(this).attr('key')])
        }) 
    })
})